{
    "name": "Legal DMS Structure Manager",
    "summary": "Managed legal document structures on top of OCA DMS",
    "version": "18.0.1.0.0",
    "category": "Document Management",
    "license": "LGPL-3",
    "author": "Mohamed Essam",
    "website": "https://essamsalem.com",
    "depends": [
        "contacts",
        "project",
        "legal_practice_management",
        "dms",
        "dms_field",
        "dms_user_role",
        "project_sequence",
        "ps_partner_code_sequence",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/dms_access_group_data.xml",
        "data/dms_directory_template_data.xml",
        "views/dms_directory_template_views.xml",
        "views/dms_smart_button_config_views.xml",
        "views/res_config_settings_views.xml",
        "views/res_partner_views.xml",
        "views/project_project_views.xml",
        "wizards/legal_dms_backfill_wizard_views.xml",
        "data/dms_smart_button_config_data.xml",
        "data/legal_dms_sync_data.xml",
    ],
    "installable": True,
    "application": False,
}
